USE DATABASE segment_events_db;

CREATE SCHEMA IF NOT EXISTS segment_events_db.transformed;

CREATE TABLE IF NOT EXISTS transformed.event_details_viewed (
	anonymous_id		STRING,
	building_id			STRING,
	building_name		STRING,
	client_name			STRING,
	context_locale		STRING,
	event				STRING,
	event_category		STRING,
	event_text			STRING,
	id					STRING,
	original_timestamp	TIMESTAMP_NTZ,
	received_at			TIMESTAMP_NTZ,
	sent_at				TIMESTAMP_NTZ,
	tenant_name			STRING,
	user_id				STRING,
	uuid_ts				TIMESTAMP_NTZ,
	_is_active			BOOLEAN,
	_created_at			TIMESTAMP_NTZ,
	_last_updated_at	TIMESTAMP_NTZ,
	_stage_record_id 	STRING,
	_loader_run_id 		VARCHAR(36),
	_ingested_at 		TIMESTAMP_NTZ,
	_staged_at 			TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS transformed.event_list_viewed (
	anonymous_id		STRING,
	building_id			STRING,
	building_name		STRING,
	client_name			STRING,
	context_locale		STRING,
	event 				STRING,
	tenant_name 		STRING,
	event_text 			STRING,
	id 					STRING,
	original_timestamp	TIMESTAMP_NTZ,
	uuid_ts 			TIMESTAMP_NTZ,
	user_id 			STRING,
	received_at 		TIMESTAMP_NTZ,
	_is_active			BOOLEAN,
	_created_at			TIMESTAMP_NTZ,
	_last_updated_at	TIMESTAMP_NTZ,
	_stage_record_id 	STRING,
	_loader_run_id 		VARCHAR(36),
	_ingested_at 		TIMESTAMP_NTZ,
	_staged_at 			TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS transformed.news_comment_added (
	anonymous_id		STRING,
	building_id			STRING,
	building_name		STRING,
	client_name			STRING,
	context_locale		STRING,
	event				STRING,
	event_text			STRING,
	id					STRING,
	news_category		STRING,
	original_timestamp	TIMESTAMP_NTZ,
	received_at			TIMESTAMP_NTZ,
	sent_at				TIMESTAMP_NTZ,
	tenant_name			STRING,
	user_id				STRING,
	uuid_ts				TIMESTAMP_NTZ,
	_is_active			BOOLEAN,
	_created_at			TIMESTAMP_NTZ,
	_last_updated_at	TIMESTAMP_NTZ,
	_stage_record_id 	STRING,
	_loader_run_id 		VARCHAR(36),
	_ingested_at 		TIMESTAMP_NTZ,
	_staged_at 			TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS transformed.news_details_viewed (
	anonymous_id		STRING,
	article_title		STRING,
	building_id			STRING,
	building_name		STRING,
	client_name			STRING,
	context_locale		STRING,
	event				STRING,
	event_text			STRING,
	id					STRING,
	news_category		STRING,
	original_timestamp	TIMESTAMP_NTZ,
	received_at			TIMESTAMP_NTZ,
	sent_at				TIMESTAMP_NTZ,
	tenant_name			STRING,
	user_id				STRING,
	uuid_ts				TIMESTAMP_NTZ,
	_is_active			BOOLEAN,
	_created_at			TIMESTAMP_NTZ,
	_last_updated_at	TIMESTAMP_NTZ,
	_stage_record_id 	STRING,
	_loader_run_id 		VARCHAR(36),
	_ingested_at 		TIMESTAMP_NTZ,
	_staged_at 			TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS transformed.news_list_viewed (
	anonymous_id		STRING,
	building_id			STRING,
	building_name		STRING,
	client_name			STRING,
	context_locale		STRING,
	event				STRING,
	event_text			STRING,
	id					STRING,
	original_timestamp	TIMESTAMP_NTZ,
	received_at			TIMESTAMP_NTZ,
	sent_at				TIMESTAMP_NTZ,
	tenant_name			STRING,
	user_id				STRING,
	uuid_ts				TIMESTAMP_NTZ,
	_is_active			BOOLEAN,
	_created_at			TIMESTAMP_NTZ,
	_last_updated_at	TIMESTAMP_NTZ,
	_stage_record_id 	STRING,
	_loader_run_id 		VARCHAR(36),
	_ingested_at 		TIMESTAMP_NTZ,
	_staged_at 			TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS transformed.user_session_active (
	anonymous_id		STRING,
	building_id			STRING,
	building_name		STRING,
	client_name			STRING,
	context_locale		STRING,
	event				STRING,
	event_text			STRING,
	id					STRING,
	original_timestamp	TIMESTAMP_NTZ,
	received_at			TIMESTAMP_NTZ,
	sent_at				TIMESTAMP_NTZ,
	tenant_name			STRING,
	user_id				STRING,
	uuid_ts				TIMESTAMP_NTZ,
	_is_active			BOOLEAN,
	_created_at			TIMESTAMP_NTZ,
	_last_updated_at	TIMESTAMP_NTZ,
	_stage_record_id 	STRING,
	_loader_run_id 		VARCHAR(36),
	_ingested_at 		TIMESTAMP_NTZ,
	_staged_at 			TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS transformed.hid_access_granted (
	anonymous_id		STRING,
	building_id			STRING,
	building_name		STRING,
	client_name			STRING,
	event				STRING,
	event_text			STRING,
	id					STRING,
	original_timestamp	TIMESTAMP_NTZ,
	received_at			TIMESTAMP_NTZ,	
	sent_at				TIMESTAMP_NTZ,	
	tenant_name			STRING,
	user_id				STRING,
	uuid_ts				TIMESTAMP_NTZ,
	_is_active			BOOLEAN,
	_created_at			TIMESTAMP_NTZ,
	_last_updated_at	TIMESTAMP_NTZ,
	_stage_record_id 	STRING,
	_loader_run_id 		VARCHAR(36),
	_ingested_at 		TIMESTAMP_NTZ,
	_staged_at 			TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS transformed.notification_viewed (
	anonymous_id		STRING,
	building_id			STRING,
	building_name		STRING,
	client_name			STRING,
	context_locale		STRING,
	event				STRING,
	EVENT_TEXT			STRING,
	id					STRING,
	original_timestamp	TIMESTAMP_NTZ,
	received_at			TIMESTAMP_NTZ,
	sent_at				TIMESTAMP_NTZ,	
	tenant_name			STRING,
	user_id				STRING,
	uuid_ts				TIMESTAMP_NTZ,
	_is_active			BOOLEAN,
	_created_at			TIMESTAMP_NTZ,
	_last_updated_at	TIMESTAMP_NTZ,
	_stage_record_id 	STRING,
	_loader_run_id 		VARCHAR(36),
	_ingested_at 		TIMESTAMP_NTZ,
	_staged_at 			TIMESTAMP_NTZ
);