-- ******************************************************************************************************************************
-- Create view
-- ******************************************************************************************************************************
CREATE OR REPLACE VIEW published.electrical_metering_ghg AS
	SELECT
		date_local,
		day_of_week,
		is_weekday,
		day_of_week_type,
		CASE WHEN scope = 'Scope 2' THEN daily_usage_kwh ELSE NULL END AS daily_usage_kwh,
		CASE WHEN scope = 'Scope 2' THEN usage_kwh_1_week_ago ELSE NULL END AS usage_kwh_1_week_ago,
		CASE WHEN scope = 'Scope 2' THEN daily_usage_kwh_4_weeks_ago ELSE NULL END AS daily_usage_kwh_4_weeks_ago,
		CASE WHEN scope = 'Scope 2' THEN daily_usage_kwh_52_weeks_ago ELSE NULL END AS daily_usage_kwh_52_weeks_ago,
		CASE WHEN scope = 'Scope 2' THEN deviation ELSE NULL END AS deviation,
		CASE WHEN scope = 'Scope 2' THEN deviation_based_on_4_weeks_ago ELSE NULL END AS deviation_based_on_4_weeks_ago,
		CASE WHEN scope = 'Scope 2' THEN energy_rating_based_on_4_weeks_ago ELSE NULL END AS energy_rating_based_on_4_weeks_ago,
		scope,
		emissions_factor,
		emissions_factor_unit,
		ghg_emissions,
		energy_source,
		asset_id,
		asset_name,
		asset_display_name,
		model_id_asset,
		level_2_model_id,
		level_2_asset_id,
		level_2_asset_name,
		level_1_asset_relationship_type,
		level_1_model_id,
		level_1_asset_id,
		level_1_asset_name,
		top_level_model_id,
		top_level_asset_id,
		top_level_asset_name,
		site_id,
		site_name,
		customer_id,
		portfolio_id,
		building_id,
		building_name,
		building_gross_area,
		building_rentable_area,
		building_type,
		last_captured_at_local,
		last_captured_at_utc,
		last_refreshed_at_utc,
		last_refreshed_at_local
	FROM transformed.electrical_metering_detail_ghg
;