-- ******************************************************************************************************************************
-- Create view
-- ******************************************************************************************************************************
CREATE OR REPLACE TABLE transformed.electrical_metering_hierarchy AS SELECT * FROM transformed.electrical_metering_assets_v;

CREATE OR REPLACE VIEW transformed.electrical_metering_hierarchy_v AS
SELECT DISTINCT
		asset_class,
		capability_id,
		capability_name,
		trend_id,
		trend_interval,
		model_id,
		unique_id,
		external_id,
		unit,
		tags,
		tags_string,
		enabled,
		capability_type,
		description,
		asset_id,
		asset_name,
		level_3_model_id,
		level_3_asset_id,
		level_3_asset_name,
		level_2_asset_relationship_type,
        level_2_model_id,
		level_2_asset_id,
		level_2_asset_name,		
		level_1_asset_relationship_type,
		level_1_model_id,
		level_1_asset_id,
		level_1_asset_name,
        top_level_model_id,
        top_level_asset_id,
        top_level_asset_name,
		model_id_asset,
		floor_id,
		level_name,
		floor_sort_order,
		site_id,
		site_name,
		time_zone,
		customer_id,
		portfolio_id,
		building_id,
		building_name,
		building_type,
		building_gross_area,
		building_rentable_area,
		capability_model_class,
		sensor_type
	FROM transformed.electrical_metering_hierarchy
;
