CREATE OR REPLACE TABLE costs.customer_lookup (
  abbreviation STRING,
  customer_code STRING,
  name STRING
);

INSERT INTO costs.customer_lookup 
VALUES
  ('axa','axa', 'AXA'),
  ('akvelon','akv','Akvelon'),
  ('akv','akv','Akvelon'),
  ('bg22','bg22', 'Bishop''s Gate'),
  ('22bishopsgate','bg22', '22 Bishopsgate'),
  ('bhp','bhp', 'BHP'),
  ('bp','bp', 'BP'),
  ('brf','brf','Brookfield Properties'),
  ('brkf','brf', 'Brookfield Properties'),
  ('brp','brf', 'Brookfield Properties'),
  ('brook','brf', 'Brookfield Properties'),
  ('brookfield','brf', 'Brookfield Properties'),
  ('bungie','bng', 'Bungie'),
  ('ddk','ddk', 'DDK Investments'),
  ('dex','dex', 'Dexus'),
  ('dfw','dfw', 'Dallas Fort Worth Airport'),
  ('dfw2','dfw', 'Dallas Fort Worth Airport'),
  ('dfwnrel','dfw', 'Dallas Fort Worth Airport'),
  ('dallas fort worth airport','dfw', 'Dallas Fort Worth Airport'),
  ('dallasfortworthairport','dfw', 'Dallas Fort Worth Airport'),
  ('durst','durst', 'Durst'),
  ('goog','goog', 'Google'),
  ('google','goog', 'Google'),
  ('fmg','fmg', 'FMG'),
  ('hsbc','hsbc', 'HSBC'),
  ('inv','inv', 'Investa'),
  ('invs','inv', 'Investa'),
  ('iiiinvesta','inv', 'Investa'),
  ('investa','inv', 'Investa'),
  ('jpmc','jpmc', 'JP Morgan Chase'),
  ('jpmorganchase','jpmc', 'JP Morgan Chase'),
  ('macquarie','mmp', 'Macquarie Group'),
  ('mmp','mmp', 'Macquarie Group'),
  ('medxcel','mdx', 'Medxcel'),
  ('mdx','mdx', 'Medxcel'),
  ('mxl','mdx', 'Medxcel'),
  ('met','met', 'Melbourne Metro'),
  ('melbournemetro','met', 'Melbourne Metro'),
  ('mining','mining', 'Mining'),
  ('msft','msft', 'Microsoft'),
  ('mstf','msft', 'Microsoft'),
  ('msft-ian','msft', 'Microsoft'),
  ('microsoft','msft', 'Microsoft'),
  ('Microsoft','msft', 'Microsoft'),
  ('microsofteastcampus','msft', 'Microsoft'),
  ('ncp','ncr', 'Newcrest'),
  ('ncr','ncr', 'Newcrest'),
  ('ncrt','ncr', 'Newcrest'),
  ('nuv','nuv', 'Nuveen'),
  ('testncr','ncr', 'Newcrest'),
  ('newcrest','ncr', 'Newcrest'),
  ('oxf','oxf', 'Oxford'),
  ('oxfd','oxf', 'Oxford'),
  ('oxford','oxf', 'Oxford'),
  ('oxform','oxf', 'Oxford'),
  ('parson','prsn','Parson'),
  ('prsn','prsn','Parson'),
  ('sanofi','snf','Sanofi'),
  ('san','snf','Sanofi'),
  ('snf','snf','Sanofi'),
  ('skws','skt', 'Strukton Worksphere'),
  ('worksphere','skt', 'Strukton Worksphere'),
  ('skt','skt', 'Strukton Worksphere'),
  ('stu','skt', 'Strukton Worksphere'),
  ('strukton','skt', 'Strukton Worksphere'),
  ('sofi','sofi', 'Hollywood Park'),
  ('hpk','sofi', 'Hollywood Park'),
  ('sofi stadium' ,'sofi' , 'Hollywood Park'),
  ('hollywoodpark' ,'sofi' , 'Hollywood Park'),
  ('tke','tke', 'Thyssenkrupp'),
  ('thyssenkrupp','tke', 'Thyssenkrupp'),
  ('tlr','tlr', 'Toll Road'),
  ('wkr','wkr', 'Walker'),
  ('wmc','wmc', 'Walmart'),
  ('wmt','wmc', 'Walmart'),
  ('walmart','wmc', 'Walmart'),
  ('watermanclark','wck', 'WatermanCLARK'),
  ('wck','wck', 'WatermanCLARK'),
  ('wrt','wrt', 'Willow Rail Tenant'),
  ('rail','wrt', 'Willow Rail Tenant')
;


CREATE OR REPLACE TABLE costs.subscription_lookup (
  subscription STRING,
  vertical STRING,
  environment_category STRING
);
  
INSERT INTO costs.subscription_lookup
VALUES 
        ('Build-PRD','Twin Creator', 'Production'),
        ('Build-DEV','Twin Creator', 'Development'),
        ('Build-UAT','Twin Creator', 'Test'),
        ('Platform-PRD','Real Estate', 'Production'),
        ('Platform-DEV','Real Estate', 'Development'),
        ('Platform-UAT','Real Estate', 'Test'),
        ('Rail-PRD','Rail', 'Production'),
        ('Rail-DEV','Rail', 'Development'),
        ('Rail-UAT','Rail', 'Test'),
        ('Rail-PRE','Rail', 'Production'),
        ('Rail-DEMO','Rail', 'Production'),
        ('Data-PRD','Data', 'Production'),
        ('Data-DEV','Data', 'Development'),
        ('Experience-PRD','Experience App', 'Production'),
        ('Experience-DEV','Experience App', 'Development'),
        ('Experience-UAT','Experience App', 'Test'),
        ('Mining-POC','Mining', 'Production'),
        ('K8S-INTERNAL','Shared', 'Development'),
        ('K8S-Internal-Environments','Shared', 'Development'),
        ('Products-Shared','Shared', 'Production'),
        ('SandboxShared','Shared', 'Development'),
        ('Sandbox-IT','IT', 'Internal'),
        ('Cyber Security','IT', 'Internal'),
        ('Willow-CoreIT','IT', 'Internal'),
        ('Willow-IT','IT', 'Internal'),
        (null,'IT', 'Internal'),
        ('dev', 'Shared', 'Development'),
        ('dev-eus-01', '', 'Development'),
        ('prd', '', 'Production')
    ;
